version: "3.8"
services:
  mule-ee:
    container_name: mule-ee-4.3.0
    image: mule-ee-4.3.0:1.0.0
    restart: always
    build:
      context: ./containers/mule-ee/
      dockerfile: Dockerfile
    environment:
      - MULE_HOME:/opt/mule
      - MULE_VERSION:4.3.0
    ports:
      - "5050:5050"
      - "5051:5051"
      - "5052:5052"
      - "5053:5053"
      - "5054:5054"
      - "5055:5055"
      - "5056:5056"
      - "5057:5057"
      - "5058:5058"
      - "5059:5059"
    volumes:
      - type: bind
        source: ~/docker/mule-ee/apps
        target: /apps