version: "3.8"
services:
  mule-ee:
    container_name: mule-ee-4.3.0
    image: mule-ee-4.3.0:1.0.0
    restart: always
    build:
      context: ./containers/mule-ee/
      dockerfile: Dockerfile
    environment:
      - MULE_HOME:/opt/mule
      - MULE_VERSION:4.3.0
    ports:
      - "5050-5059:5050-5059"
    volumes:
      - type: bind
        source: ~/docker/mule-ee/apps
        target: /apps

  jenkins:
    container_name: jenkins
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./containers/jenkins
    volumes:
      - ./containers/jenkins/data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_USER=CHANGE_ME
      - JENKINS_PASS=CHANGE_ME
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
  nexus:
    container_name: nexus
    image: sonatype/nexus3
    restart: always
    volumes:
      - ./containers/nexus/data:/sonatype-work
    ports:
      - "8081:8081"
