#
# example Dockerfile PostgreSQL
#

FROM postgres:alpine
#ENV POSTGRES_USER=sms_admin
#ENV POSTGRES_PASSWORD=SMS_4dm1n
#ENV POSTGRES_DB=sonar

#EXPOSE 5432

VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql"]

