name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MULE_HOME: ${{ secrets.MULE_HOME }}
  MULE_VERSION: ${{ secrets.MULE_VERSION }}
  JENKINS_USER: ${{ secrets.JENKINS_USER }}
  JENKINS_PASS: ${{ secrets.JENKINS_PASS }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create dirs
      run: sh ./create-dirs.sh
    - name: Build the Docker images
      run: docker-compose up -d
    - name: Check results
      run: docker ps
